- name: Installer Zabbix Agent 2                         # Titre du play
  hosts: zabbix_agents_pmox                              # Groupe d'hôtes ciblé (inventaire)
  become: yes                                            # Exécuter avec privilèges (root)

  vars:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu24.04_all.deb"  # Paquet "release" qui ajoute le dépôt Zabbix
    zabbix_server_ip: "10.8.16.170"                      # IP du serveur Zabbix (passif/actif)

  tasks:
    - name: Télécharger le dépôt Zabbix
      ansible.builtin.get_url:
        url: "{{ zabbix_repo_url }}"                     # URL du .deb du dépôt Zabbix
        dest: /tmp/zabbix-release.deb                    # Chemin local temporaire

    - name: Installer le dépôt Zabbix
      ansible.builtin.apt:
        deb: /tmp/zabbix-release.deb                     # Installe le .deb (ajoute sources + clé)
        state: present

    - name: Mettre à jour les paquets APT
      ansible.builtin.apt:
        update_cache: yes                                # Équivalent à "apt-get update"

    - name: Installer zabbix-agent2
      ansible.builtin.apt:
        name: zabbix-agent2                              # Paquet officiel agent 2
        state: present

    - name: Configurer le serveur Zabbix
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Server="                               # Cherche la directive "Server="
        line: "Server={{ zabbix_server_ip }}"            # Serveurs autorisés (mode passif)
        backup: yes                                      # Sauvegarde le fichier avant modification

    - name: Configurer le serveur actif Zabbix
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^ServerActive="                         # Cherche "ServerActive="
        line: "ServerActive={{ zabbix_server_ip }}"      # Cible pour checks actifs (port 10051 par défaut)
        backup: yes

    - name: Configurer le Hostname
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Hostname="                             # Cherche "Hostname="
        line: "Hostname={{ inventory_hostname }}"        # Nom reporté à Zabbix (pris de l'inventaire Ansible)
        backup: yes

    - name: Configurer le HostMetadata pour auto-registration
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^HostMetadata="                         # Cherche "HostMetadata="
        line: "HostMetadata=linux"                       # Métadonnée utilisée par vos règles d'auto-enregistrement
        backup: yes

    - name: Redémarrer et activer l’agent Zabbix 2
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: restarted                                 # Redémarre pour appliquer la configuration
        enabled: yes                                     # Active le service au démarrage
